name: Build Django Telegram Bot

on:
  push:
    branches: '*'
    tags:
        - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["2.2.*", "3.0.*", "3.1.*", "3.2.*"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry run pip install --force-reinstall django==${{ matrix.django-version }}
    - name: Linting
      run: |
        poetry run flake8
    - name: Testing
      run: |
        poetry run pytest
    - name: Fix coverage report for Sonar
      run: |
        sed -i 's/\/home\/runner\/work\/telegram-django\/telegram-django\//\/github\/workspace\//g' coverage.xml
    - name: SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}